#!/usr/bin/env bash

#******************************************************************************
# Copyright 2019 the original author or authors.                              *
#                                                                             *
# Licensed under the Apache License, Version 2.0 (the "License");             *
# you may not use this file except in compliance with the License.            *
# You may obtain a copy of the License at                                     *
#                                                                             *
# http://www.apache.org/licenses/LICENSE-2.0                                  *
#                                                                             *
# Unless required by applicable law or agreed to in writing, software         *
# distributed under the License is distributed on an "AS IS" BASIS,           *
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    *
# See the License for the specific language governing permissions and         *
# limitations under the License.                                              *
#******************************************************************************/

#==============================================================================
# SCRIPT:   bashrc
# AUTOHR:   Markus Schneider
# DATE:     2019-06-01
# REV:      1.0.0
# PLATFORM: Noarch
# PURPOSE:  Set the project environment for running dockerw scripts.
#==============================================================================

export ORIGIN="node"
export ENTITY="skeleton04"
export TAG="1.0.0"
export NAME="skeleton04"
export IMAGE="$ORIGIN/$ENTITY:$TAG"

#export MONGO_HOSTNAME="mongodb"
export MONGO_HOSTNAME="localhost"
export MONGO_INITDB_ROOT_USERNAME=admin
export MONGO_INITDB_ROOT_PASSWORD=changeme
export MONGO_INITDB_DATABASE=myapp

export CWD=$(pwd)
PATH=$CWD/../../dockerw:$PATH

source $CWD/../../dockerw/cmdrc
